### ISSUE TITLE
go-resty import requires replacement propagation

### ISSUE THREAD

**Issue by kevingentile** [gomorpheus/morpheus-go-sdk#2]
# Scenario

Import `morepheus-go-sdk` into a project and tidy modules. Task fails due to invalid mapping of indirect dependency. The existing import targets `v1.12` but the replacement points to `v1.11`. Workaround is to propagate the replacement in the downstream project.

### go.mod
```
module mymodule

go 1.14

require github.com/gomorpheus/morpheus-go-sdk v0.0.0-20191127142315-97a336ca228d
```

```
$ go mod tidy
go: github.com/gomorpheus/morpheus-go-sdk@v0.0.0-20191127142315-97a336ca228d requires
        github.com/go-resty/resty@v1.12.0: parsing go.mod:
        module declares its path as: gopkg.in/resty.v1
                but was required as: github.com/go-resty/resty
```

## Valid build
```
module mymodule

go 1.14

require github.com/gomorpheus/morpheus-go-sdk v0.0.0-20191127142315-97a336ca228d

replace github.com/go-resty/resty => gopkg.in/resty.v1 v1.12.0
```

```
$ go mod tidy
go: finding module for package gopkg.in/resty.v1
go: found gopkg.in/resty.v1 in gopkg.in/resty.v1 v1.12.0
go: gopkg.in/resty.v1@v1.12.0 used for two different module paths (github.com/go-resty/resty and gopkg.in/resty.v1)
```

`go-resty` [documentation states](https://github.com/go-resty/resty#supported-go-versions) modules are supported from go v1.10+ but this appears to be misleading. May want to entertain upgrading to V2.

# Replacement target
The [existing module replacement](https://github.com/gomorpheus/morpheus-go-sdk/blob/97a336ca228de720c03272a1042aea9a0d917c0f/go.mod#L8) is pointing to `v1.11` of go-resty as the target for the import of `v1.12`:

```
replace github.com/go-resty/resty => gopkg.in/resty.v1 v1.11.0
```

should be

```
replace github.com/go-resty/resty => gopkg.in/resty.v1 v1.12.0
```

**Comment by jamesdickson6** [comment]
Changed it to:
replace github.com/go-resty/resty => gopkg.in/resty.v1 v1.12.0

**Comment by kevingentile** [comment]
Still having issues with replacement propagation.

```
module mymodule

go 1.14

require (
	github.com/gomorpheus/morpheus-go-sdk v0.0.0-20200407214633-a8c5318e32b7
	golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e // indirect
)

//TODO https://github.com/gomorpheus/morpheus-go-sdk/issues/2
// replace github.com/go-resty/resty => gopkg.in/resty.v1 v1.12.0

```

```
$ go mod tidy
go: github.com/gomorpheus/morpheus-go-sdk@v0.0.0-20200407214633-a8c5318e32b7 requires
        github.com/go-resty/resty@v1.12.0: parsing go.mod:
        module declares its path as: gopkg.in/resty.v1
                but was required as: github.com/go-resty/resty
```

**Comment by jamesdickson6** [comment]
Ah I see. This does not appear to be an issue on go 1.13.4. 
I'll have to look at this again later.

**Comment by jamesdickson6** [comment]
@kevingentile I commited the changes after go mod tidy.
Want to give it another try for me?

**Comment by kevingentile** [comment]
@jamesdickson6 Thanks for taking another look. Yeah, I'm still running into issues. I can copy the replacement line into my `go.mod`, but it's not intuitive.

Related issues:
https://github.com/go-resty/resty/issues/178
https://github.com/go-resty/resty/issues/230 

I've created a sample app targeting go 1.13 and 1.14 you can find [here](https://github.com/kevingentile/morpheus-go-sample)

**Comment by jamesdickson6** [comment]
The repo has been upgraded to go 1.14 and resty v2. I think this issue is gone now.
Thanks for the help!
